development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      uri: <%= ENV['MONGODB_URI'] %>

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>